version: '3.8'

services:
  configserver:
    image: "steeltoeoss/config-server:3"
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./config
        target: /config
    ports:
      - "8888:8888"
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - 5672:5672
      - 15672:15672
