spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
mysql:
  client:
    database: bluepawdb
    server: localhost
    port: 3306
    username: bluepawadmin
    password: "m@n5b3stfr13nd"
