// <auto-generated />
using System;
using BluePaw.Administration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BluePaw.Administration.Migrations
{
    [DbContext(typeof(BluePawDbContext))]
    [Migration("20211026140001_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("BluePaw.Administration.Data.AdministrationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("completed");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("Request")
                        .HasColumnType("longtext")
                        .HasColumnName("request");

                    b.HasKey("Id");

                    b.ToTable("administration_requests");
                });

            modelBuilder.Entity("BluePaw.Administration.Data.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("OwnerName")
                        .HasColumnType("longtext")
                        .HasColumnName("owner_name");

                    b.Property<string>("OwnerPhone")
                        .HasColumnType("longtext")
                        .HasColumnName("owner_phone");

                    b.Property<string>("Species")
                        .HasColumnType("longtext")
                        .HasColumnName("species");

                    b.HasKey("Id");

                    b.ToTable("patients");
                });
#pragma warning restore 612, 618
        }
    }
}
